variables:
    GITLAB_CI_IMAGE_DEBIAN: 'debian:buster'
stages:
  # The piplines to run in CI
  - doc
  - test
  - build 
  
doc:
  # generate the documentation
  image: ${GITLAB_CI_IMAGE_DEBIAN}
  stage: doc
  before_script:
    # Actions to perform before the test
    - apt-get -q update
    - apt-get -qy install doxygen
  script:
    - make doc
    - mv sat/doc/html/ public/
    - echo "API documentation should be accessible soon"
  artifacts:
    paths:
      - public
  
  
test:
  # The test stage.
  image: ${GITLAB_CI_IMAGE_DEBIAN}
  stage: test
  before_script:
    # Actions to perform before the test
    - apt-get -q update
    - apt-get -qy install gnupg libcurl4
    - >
      apt-get -qy install
      build-essential
      cmake
      doxygen
      git
      gnuradio-dev
      gr-soapy
      libboost-date-time-dev
      libboost-dev
      libboost-filesystem-dev
      libboost-program-options-dev
      libboost-regex-dev
      libboost-system-dev
      libboost-test-dev
      libboost-thread-dev
      libjsoncpp-dev
      liborc-0.4-dev
      libpng++-dev
      libvorbis-dev
      pkg-config
      python3-dev
      python3-six
      swig
  script:
    # Actions to perform to run the test
    - pwd
    - ls
    - mkdir -p build
    - cd build
    
      
