variables:
    GITLAB_CI_IMAGE_DEBIAN: 'debian:buster'
stages:
  # The piplines to run in CI
  - test 
  - doc
  
doc:
  # generate the documentation
  image: ${GITLAB_CI_IMAGE_DEBIAN}
  stage: doc
  before_script:
    # Actions to perform before the test
    - apt-get -q update
    - apt-get -qy install doxygen graphviz
  script:
    - cd sat
    - doxygen rules/Doxyfile
    - cd ..
    - mv sat/doc/html/ public/
    - echo "API documentation should be accessible soon"
  artifacts:
    paths:
      - public
  
  
test:
  # The test stage.
  image: ${GITLAB_CI_IMAGE_DEBIAN}
  stage: test
  before_script:
    # Actions to perform before the test
    - apt-get -q update
    - apt-get -qy install build-essential gcc-arm-none-eabi 
  script:
    # Actions to perform to run the test
    - pwd
    - ls
    - make DEBUG=1
  
    
      
